### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by carrsh** [OHSU-Library/github-tutorial#14]
Getting people to respond to my emails!

**Comment by f0rer0** [comment]
http://stackoverflow.com/questions/23904274/is-there-a-way-to-get-colored-text-in-github-flavored-markdown

**Comment by dunka434** [comment]
I recommend a robot!

**Comment by carrsh** [comment]
![robot](https://cloud.githubusercontent.com/assets/24946701/22758961/a38a6996-ee05-11e6-8792-232f8051a868.png)
