### ISSUE TITLE
Faulty cookie recipe needs oven temperature

### ISSUE THREAD

**Issue by jmcmurry** [OHSU-Library/github-tutorial#3]
Dan's [cookie recipe](https://gist.github.com/DoctorBud/72c7181f7c9d63350a4aa7e50de21b81#file-cookierecipe-md) doesn't include the baking temperature.

**Comment by wilkerst** [comment]
But raw cookie dough is the best!

**Comment by nicolevasilevsky** [comment]
+1 @wilkerst

**Comment by jmcmurry** [comment]
+1
